server:
  servlet:
    context-path: /
  port: 9527

#logback自定义路径配置
logback:
  logdir: D:/Opc_Center_Java/log
  appname: sen

#mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath*:mappers/*/*.xml

#多数据源配置
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: sa
          password: cJ3fsxzfyj
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.137.23;DatabaseName=Opc_Config_DB

influxdb:
  url: http://192.168.137.27:8086
  user: admin
  password: admin
  database: Opc_RealTimeDB
